version: "3.7"

services:
  magane-server:
    container_name: magane-server
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./database:/app/database:rw
    ports:
      - 5000:5000
    restart: unless-stopped
